### ISSUE TITLE
Translate now in after:now

### ISSUE THREAD

**Issue by dhcmega** [MarcoGomesr/laravel-validation-en-espanol#11]
Hi, maybe this is a Laravel limitation and this array is ok.
But this rule:
`'solve_by' => 'required_without:ticket_type_id|after:now',`

Gives me:
`El campo fecha de solución debe ser una fecha después de now.`

How do I translate `now`?
Great work btw
Thanks!

**Comment by MarcoGomesr** [comment]
♥️
